# Generated by Django 3.1.7 on 2021-09-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookticket', '0004_auto_20210906_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Phone',
            field=models.IntegerField(max_length=100),
        ),
    ]
