# Generated by Django 3.1.7 on 2021-09-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookticket', '0007_auto_20210908_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='Phone',
            field=models.CharField(max_length=33),
        ),
    ]
