# Generated by Django 3.1.7 on 2021-09-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookticket', '0008_auto_20210908_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trains',
            name='Train_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
