# Generated by Django 3.1.7 on 2021-09-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookticket', '0010_auto_20210909_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='Departure_Time',
            field=models.CharField(max_length=5),
        ),
    ]
